name: Initialize workarea
runs:
  using: composite
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: 3.11.4
    - name: Install Poetry
      shell: bash
      run: pip install poetry>=1.3.1
    - name: Cache Poetry virtualenv
      uses: actions/cache@v3
      id: cache
      with:
        path: ~/.virtualenvs
        key: poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          poetry-${{ hashFiles('**/poetry.lock') }}
    - name: Set Poetry config
      shell: bash
      run: |
        poetry config virtualenvs.in-project false
        poetry config virtualenvs.path ~/.virtualenvs
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: poetry install
